services:
  # truyen-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #     - PORT=3000
  #     - DB_PORT=5678
  #     - DB_HOST=postgres_db
  #   volumes:
  #     - ./src:/usr/src/app/src
  postgres_db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ntruyen
    ports:
      - '5678:5432'
  # redis_nt:
  #   image: redis
  #   ports:
  #     - '6379:6379'
# NODE_ENV=development
# PORT=3000
# DB_PORT=5678
# DB_HOST=postgres_db
# DB_USER=postgres
# DB_PASS=postgres
# DB_NAME=ntruyen
# DB_TYPE=postgres
# REDIS_HOST=localhost
# REDIS_PORT=6379
# REDIS_TTL=86400

# # This was inserted by `prisma init`:
# # Environment variables declared in this file are automatically made available to Prisma.
# # See the documentation for more detail: https://pris.ly/d/prisma-schema#accessing-environment-variables-from-the-schema

# # Prisma supports the native connection string format for PostgreSQL, MySQL, SQLite, SQL Server, MongoDB and CockroachDB.
# # See the documentation for all the connection string options: https://pris.ly/d/connection-strings

# DATABASE_URL="postgresql://postgres:postgres@localhost:5678/ntruyen?schema=public"
